services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: client
    image: gauntlet-client:latest
    ports:
      - "9001:9000"

  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: server
    image: gauntlet-server:latest
    ports:
      - "9000:9000"
