services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.debug
      args:
        SERVICE: client
    ports:
      - "9001:9000"
      - "2345:40000"
    security_opt:
      - seccomp:unconfined

  server:
    build:
      context: .
      dockerfile: Dockerfile.debug
      args:
        SERVICE: server
    ports:
      - "9000:9000"
      - "2346:40000"
    security_opt:
      - seccomp:unconfined
